services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'
    healthcheck:
      test: ['CMD', 'pg_isready', '--host=localhost', '--username=directus']
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./:/directus/extensions/directus-image-scout
    depends_on:
      database:
        condition: service_healthy
    environment:
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'false'

      EXTENSIONS_AUTO_RELOAD: true
      MARKETPLACE_TRUST: 'all'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'password'
      # PUBLIC_URL: 'https://directus.example.com'
